danielg-projectOne/danielg-projectOne/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using danielg_projectOne.DataModel;
using danielg_projectOne.DataModel.Repositories;
using danielg_projectOne.Library;
using danielg_projectOne.Models;
using Microsoft.AspNetCore.Mvc;


namespace danielg_projectOne.Controllers
{
    public class ManagerController : Controller
    {
        /// <summary>
        /// Create the Repository field that will search the DB for this controller
        /// </summary>
        public IManagerRepository Repo { get; }

        /// <summary>
        /// Assign a Repository to the Controller 
        /// </summary>
        /// <param name="repo"></param>
        public ManagerController(IManagerRepository repo) =>
            Repo = repo ?? throw new ArgumentNullException(nameof(repo));


        // GET: /<controller>/
        public IActionResult Index(string search = "")
        {
            IEnumerable<StoreViewModel> vmStores = new List<StoreViewModel>();
            try
            {
                // Get the list of all stores matching the sercch string
                List<Location> stores = Repo.GetAllStoresByLocation(search);

                vmStores = stores.Select(s => new StoreViewModel
                {
                    ID = s.Id,
                    Location = s.CityLocation
                });
            }
            catch
            {
                return RedirectToAction("Index", "Home");
            }
            return View(vmStores);
        }

        //GET: Manager/Home/1
        public IActionResult Home(int id = 0)
        {
            if (id == 0)
            {
                // No customer was able to sign in, this shouldnt happen
            }
            // Create list of viewmodel to pass to view method in return
            IEnumerable<StoreOrderViewModel> storeOrders = null;

            try
            {

                var storeProducts = Repo.GetProducts();
                var storesOrders = Repo.GetStoresOrders(id);

                storeOrders = storesOrders.Select(c => new StoreOrderViewModel
                {
                    ID = c.OrderID,
                    Customer = c.Customer.Name,
                    Cost = c.CalculateTotal(storeProducts),
                    Date = c.Date
                });

            }
            catch 
            {
                return RedirectToAction(nameof(Index));
            }


            return View(storeOrders);
        }
    }
}

danielg-projectOne/danielg-projectOne/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dumb McDonald's</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Dumb McDonald's</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Manager" asp-action="Index">Managers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - danielg_projectOne - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>